apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mediscan-cluster
  region: us-east-1

iam:
  serviceRoleARN: "arn:aws:iam::016696860649:role/LabRole"

managedNodeGroups:
  - name: standard-nodes
    instanceType: t3.large
    desiredCapacity: 2
    iam:
      instanceRoleARN: "arn:aws:iam::016696860649:role/LabRole"